eval "$(dircolors -b)"

alias ..='cd ..'
alias cls='clear'
alias chgrp='chgrp -v'
alias chmod='chmod -v'
alias chown='chown -v'
alias cp='cp -iv'
alias gits='git status'
alias ls='LC_COLLATE=C ls --color=auto --group-directories-first -F'
alias l='ls -lhsi'
alias la='ls -lhsia'
alias ll='ls -lhsi'
alias md='mkdir -pv'
alias mv='mv -iv'
alias rm='rm -iv'
